vadimdemedes/dom-chef

index.js
=> Drop explicit type casting

index.js, package.json
`dom-chef` currently builds to 50.5KB because of Lodash extensive comments and flexibility. Refined GitHub ships dependencies unminified so we get the whole 50K. A bit of a waste, I'd say.
Try:
```sh
$ npm i package-size -g
$ package-size dom-chef . --es6
package   size     minified  gzipped
dom-chef  50.5 kB  9.54 kB   3.48 kB
.         3.21 kB  1.77 kB   736 B
```
=> Replace lodash modules with lightweight alternatives

index.js, test.js
```jsx
const use = <use xlinkHref="#stuff">;
```
It's `xlinkHref` instead of `xlink:href` as shown in:
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#notable-enhancements
=> Add support for xlink:href

index.js, test.js
> [addEventListener] replaces the existing click event listener(s) on the element if there are any. Other events and associated event handlers such as blur (onblur), keypress (onkeypress), and so on behave similarly.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Older_way_to_register_event_listeners
=> Use addEventListener instead of the properties

index.js
I was getting this error after updating from v1:
=> Restore SVG classes compatibility

index.js, package.json
8 fewer loops and 25% fewer dependencies = 15% KB gzip savings and ∞ speed improvements.
We could go the extra mile and use 3 plain `for` loops as well.
=> One loop to rule them all

package.json
AVA automatically loads the specified babel config + probably we should only apply the es-module transform, otherwise we might accept Node > 4 code without realizing it (because tests pass, but code doesn't actually work on Node 4 installs)
=> Drop babel preset/register

index.js, test.js
```js
const template = document.createElement('template');
template.innerHTML = 'Hello, <strong>World!</strong>';
<a>{template.content}</a>
```
=> Add support for document fragments as children of elements

index.js, test.js
`CSSStyleDeclaration.setProperty()` calls accept the hyphen-case of the
CSS property name to be modified. Since we are forwarding the `style`
object of the JSX DOM element directly (which has camelCased names),
styles with more than one word in the property name won't be applied.
The `style.cssPropertyName = 'value';` variant does accept a camelCase
name, so replacing the former with the latter should fix the bug.
Closes #23.
=> Replace `.setProperty` in favor of `.propertyName = value`

index.js, package-lock.json, package.json, readme.md, test.js
Closes #18 
Now that Babel 7 was officially released a few days ago, I think we can add fragments support here.
How do you feel about it? Do you think we should say something different in the README? How about the implementation?
=> Add support for JSX fragments

index.js, package.json, readme.md, test.js
Use as:
```js
import {React} from 'dom-chef';
```
Source: https://github.com/Microsoft/TypeScript/issues/20469
Useful for: https://github.com/sindresorhus/refined-github/pull/1726
cc @sindresorhus
=> Add support for DocumentFragment in TypeScript

index.d.ts, index.js, package-lock.json, package.json, react.js, readme.md
When I published v3.4.x patches, I did so in a hurry to avoid breaking existing users, but I just thought of a better solution.
v3.4 worked correctly in browsers but it was breaking node-base environments (like tests) because it expected `global.DocumentFragment` at `require` time.
This PR will use `typeof` before using it and when negative, it will return an empty function. This function is never used. If `dom-chef` is actually run, it will require `DocumentFragment` to be on `global` anyway: 
https://github.com/vadimdemedes/dom-chef/blob/3ada48d0a8504854b70d3f0d43ad6f7c645b8b6a/index.js#L41
---
For this reason, I thought of bringing it back to the main file and enable various and simplified usages:
```js
// Standard until 3.4
const {h} = require('dom-chef')
import {h} from 'dom-chef' …
```
=> Improve pragma-less usage

index.d.ts, index.js, test.js
For example:
```jsx
const header = document.querySelector('h3');
return <span>{header.firstChild}</span>
```
`.appendChild` supports generic `Node` objects, which includes `Element`, `DocumentFragment` and `TextNode`: https://github.com/Microsoft/TypeScript/blob/9d3707d671592d030386956c9ce39e539b8d0972/src/lib/dom.generated.d.ts#L10431
=> Add support for TextNode children

package.json
Hey,
Currently, type definitions are not published to `npm`. This PR fixes that.
Thanks!
=> Publish type definitions

index.js, test.js
Closes #33 
Add supports for:
```jsx
<a disabled={false}>
// Same as <a>
```
and
```jsx
<a disabled={true}>
// Same as <a disabled> instead of <a disabled="true">
```
If the intended attribute value is `"true"`, then it should be passed as a string. React seems to match this behavior:
https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/client/DOMPropertyOperations.js#L161-L162
Although technically only on a whitelist:
https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/shared/DOMProperty.js#L279-L312
=> Handle boolean attributes correctly

index.js, test.js
Fixes https://github.com/vadimdemedes/dom-chef/issues/43
I noticed that initially `dom-chef` was expected to appen `undefined` as a string. This PR changes this expectation to align it with React's behavior.
=> Skip `undefined` children

index.ts, package.json, readme.md, test.js
Closes #55 
This introduces a very simple support for element-returning functions. My use case would be using an icon library with DOM-returning functions which I can then customize:
```js
import {BirdIcon} from 'icons';
document.body.append(<BirdIcon width={32} height={32} className="margin-2"/>);
```
AFAIK in React `<Component prop={1}>` would pass `{prop: 1}` to `Component`. The component itself will then handle the props.
In `dom-chef's` world this wouldn't make sense props exist solely as attributes on the generated element, _not_ as a JavaScript object. That would be a leaky abstraction.
My resolution is that if one wants `Component` to receive `{prop: 1}` they should not use JSX.
CSS classes are appended to any existing ones, unlike other attributes. This is not overridable. …
=> Add support for `<Function />`

index.ts, readme.md
This improves compatibility for simple React Functional Components like [@primer/octicon-react](https://www.unpkg.com/browse/@primer/octicons-react@10.0.0/dist/index.esm.js):
=> Pass `defaultProps` to element function

.github/workflows/esm-lint.yml
1. Enables Webpack 5 support in linter
2. Starts using [ghat](https://github.com/fregante/ghat) to simplify the sharing/updating of the workflow.
New source: https://github.com/fregante/ghatemplates#esm-lint
=> Meta: Use `ghat` to update `esm-lint`

index.ts, package.json
Fixes #36 
adding: 
```ts
declare global {
namespace JSX {
interface Element extends HTMLElement {}
}
}
```
ensures that typescript doesn't complain when you write code like this:
```ts
const app = <div>app</div>;
document.body.appendChild(app);
```
```ts
interface JSXElementClassDocumentFragment extends DocumentFragment, JSX.ElementClass {}
interface Fragment {
prototype: JSXElementClassDocumentFragment;
new (): JSXElementClassDocumentFragment;
}
...
export const Fragment = (typeof DocumentFragment === 'function' ? DocumentFragment : () => {}) as Fragment;
```
exports `Fragment` so that you can import it from `dom-chef` and typescript doesn't complain.
now you can use fragments like this:
```tsx
import { h, Fragment } from 'dom-chef';
document.body.appendChild(
<Fragment>
<div>2</div> …
```
=> Include TypeScript types for JSX

.github/workflows/esm-lint.yml, readme.md
Initially I just want to correct a typo:
```diff
- This has the advantage of enabling `Fragment` support with the TypeScript compiler, if you're using it compile JSX without Babel. Related issue: https://github.com/Microsoft/TypeScript/issues/20469
+ This has the advantage of enabling `Fragment` support with the TypeScript compiler, if you're using it to compile JSX without Babel. Related issue: https://github.com/Microsoft/TypeScript/issues/20469
```
Then I realized that piece of info is outdated, so I added a extra section for detailed TypeScript compiler config one may need.
=> Add detailed TypeScript compiler config

index.ts, tests/index.tsx
Closes #33 
Fixes support for attributes that allow `"false"` values:
```tsx
<div contentEditable={false}>
```
Generates:
```html
<div contenteditable="false"/>
```
=> Add support for booleanish string attributes
